### PR TITLE
Feature/gh 99 more clang versions

### LINKED ISSUE #99: Adding more clang versions to the testing pipelines
## Feature Request
The new incoming PR comes with changes on our testing workflow, specially targeting clang, since we're still unable to solve issues with the other compilers ATM.

The idea is that, since Clang is our base users target, it would be nice have a wide range of support for it's tasks.

For that reason, the purpose is to add more versions in our pipelines, at least Clang `14, 15 (this is the current), 16 and 17`, keeping an eye on the upcoming release (Clang 18).

We could create a new workflow for each version, or even better, in the action, one of those that are run in loop.
If we can't parallelize that job, we could create then new workflows (even if it sounds as a copy-paste) but will allows us to run concurrently the tests and not having an extremely large pipeline for testing every compiler (since most of them must be installed manually, and then compiling the code for every test) 

Well, technically we could make a caché of the build, and then run the tests with the different Clang versions, and if it's in parallel (separated workflows), we already have the swatinem action that caches the builds on different iterations.

### PR DESCRIPTION
**Pull request by gbm25**
Closes #99

### CODE REVIEW

**Comment by Pyzyryab** [comment]
@gbm25 I suggest you to skip the `Clang 14` pipeline, since we won't support `Clang 14` directly anymore. The user still can use `Zork++` with `Clang 14`, but it won't be our target to offer support them, since we've already implemented a lot of features that aren't available on that frontend version (like module partitions, for example).

**Comment by Pyzyryab** [comment]
@gbm25 and when you can, open the pull request. Changes are ready to be merged when you commit that workflow without `Clang 14`. And this changes won't generate a release, so it's fine.

**Comment by gbm25** [comment]
> @gbm25 and when you can, open the pull request. Changes are ready to be merged when you commit that workflow without `Clang 14`. And this changes won't generate a release, so it's fine.

I removed `Clang 14` from the tested versions.
I also changed the job name to reflect the Clang version being tested, to make it easier to identify in case of failure.

**Review by Pyzyryab — APPROVED** [review]
In size

**Pull request merged**
