### PR TITLE
Fix failure to build modules with GCC

### PR DESCRIPTION
**Pull request by Property404**
GCC module build was missing `-fmodules-ts`

### CODE REVIEW

**Comment by TheRustifyer** [comment]
Hello @Property404 
First of all, thanks for the `PR` is very much appreciated. And sorry for the delay on review.

Some considerations:

- `GCC` is discarded from our main tasks, since their modules implementation was the past year, by far, the most incomplete of the big three ones.
- Also, it fails in quite different situation due to issues of `Zork` generating commands against their `gcm.cache` (the standard path where they stored the system BMI's)
- The `ts` flag means `technical-specification`. I am not sure if they already mark such flag as deprecated (even that we don't mind to introduce breaking changes with legacy compilers versions), since `Zork` is already in a development stage, and we don't plan to support for too long compilers intermediate implementations of standard `C++` modules.

Even tho, you've spot a bug. But before approve the changes (and these days I am not unable to use any kind of computer) I only would like to know the `OS` and the `GCC` version you've used to found the bug.

Thanks again.

**Comment by Property404** [comment]
Hi @TheRustifyer 

OS: Fedora 40 (beta)
GCC: 14.0.1 20240328 (Red Hat 14.0.1-0)

Reproduction steps:
1. `zork new <project>`
2. Change configuration to GCC in zork_clang.toml
3. `zork build`

**Comment by TheRustifyer** [comment]
> Hi @TheRustifyer
> 
> OS: Fedora 40 (beta) GCC: 14.0.1 20240328 (Red Hat 14.0.1-0)
> 
> Reproduction steps:
> 
>     1. `zork new <project>`
> 
>     2. Change configuration to GCC in zork_clang.toml
> 
>     3. `zork build`

Sorry, but I meant, does the example that is generated after `zork new` runs successfully?

**Comment by Property404** [comment]
`zork build` fails without my patch because GCC does not build the modules. After the patch, everything works as expected  

If I don't modify `zork_clang.toml`, it will try to build with Clang, which also fails on my system due to an unrelated issue

**Comment by TheRustifyer** [comment]
> `zork build` fails without my patch because GCC does not build the modules. After the patch, everything works as expected  
> 
> If I don't modify `zork_clang.toml`, it will try to build with Clang, which also fails on my system due to an unrelated issue

Note that you can pass the `compiler` flag with the `GCC` value, so you can create the template with the target compiler.

**Review by TheRustifyer — APPROVED** [review]

**Comment by TheRustifyer** [comment]
> If I don't modify `zork_clang.toml`, it will try to build with Clang, which also fails on my system due to an unrelated issue

Please, feel free to open a new issue with the details if you have time. I am able to found some issues from `clang-19` onwards, directly built from the *llvm* **main** branch. Everything's fine up until `clang-17` as far as I know

**Comment by TheRustifyer** [comment]
> GCC module build was missing `-fmodules-ts`

Feel free to `squash and merge` whenever you want. Good catch on the bug, and thanks for the work!

**Comment by TheRustifyer** [comment]
> @TheRustifyer Rebased
> 
> As for the clang issue, I haven't gotten clang 18 on Fedora to compile modules with or without Zork, so I don't think that's a Zork issue. I'm sure there's a fix for that, I just haven't looked into it very far

Interesting, I haven't access to a clean `clang-18` build, so I couldn't check. I hope I can add it to the actions, so we can check if it's working from the CI process directly.

This afternoon I'll check the `clang-19` version on `Unix` variants.
Sure that on `Windows` `clang-19` doesn't build, since the `modulemap` trick is bringing headers that are triggering compile errors.

BTW, you have everything approved again :)

**Pull request merged**
